// Command apigen generates Fiber v3 route registration code from either:
//   - an OpenAPI spec (--spec) with x-service-name extensions, or
//   - a config.yaml (--config) with providers and routes sections.
//
// Config mode supports both filter-mode transforms (single upstream) and
// provider-mode transforms (multiple upstreams via aggregator). The mode is
// auto-detected by checking if the jsonata file uses $fetch() calls.
//
// Usage:
//
//	go run ./cmd/apigen \
//	  --spec=api/openapi.yaml \
//	  --output=cmd/server/routes_gen.go \
//	  --package=main \
//	  --generated-pkg=github.com/example/project/internal/generated
//
//	go run ./cmd/apigen \
//	  --config=config.yaml \
//	  --jsonata-dir=internal/generated \
//	  --output=cmd/server/routes_gen.go \
//	  --package=main \
//	  --generated-pkg=github.com/example/project/internal/generated
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

func main() {
	spec := flag.String("spec", "", "path to OpenAPI YAML file (legacy mode)")
	config := flag.String("config", "", "path to config.yaml (provider-aware mode)")
	jsonataDir := flag.String("jsonata-dir", "", "directory containing .jsonata files (used with --config)")
	output := flag.String("output", "", "path for the generated .go file")
	pkg := flag.String("package", "main", "Go package name for the generated file")
	genPkg := flag.String("generated-pkg", "", "import path of the generated transform package")
	flag.Parse()

	if *output == "" || *genPkg == "" {
		fatal("--output and --generated-pkg are required")
	}

	hasSpec := *spec != ""
	hasConfig := *config != ""
	if !hasSpec && !hasConfig {
		fatal("either --spec or --config is required")
	}
	if hasSpec && hasConfig {
		fatal("--spec and --config are mutually exclusive")
	}

	var src []byte
	var routeCount int
	var sourceFile string

	if hasSpec {
		sourceFile = *spec
		routes, err := parseSpec(*spec)
		if err != nil {
			fatal("parsing spec: %v", err)
		}
		routeCount = len(routes)
		src, err = generateSpecRoutes(routes, *pkg, *genPkg)
		if err != nil {
			fatal("generating routes: %v", err)
		}
	} else {
		sourceFile = *config
		routes, err := parseConfig(*config, *jsonataDir)
		if err != nil {
			fatal("parsing config: %v", err)
		}
		routeCount = len(routes)
		src, err = generateConfigRoutes(routes, *pkg, *genPkg)
		if err != nil {
			fatal("generating routes: %v", err)
		}
	}

	if err := os.WriteFile(*output, src, 0o644); err != nil {
		fatal("writing output: %v", err)
	}

	fmt.Fprintf(os.Stderr, "apigen: %s -> %s (%d routes)\n", sourceFile, *output, routeCount)
}

// --- OpenAPI spec mode (backward compatible) ---

type specRoute struct {
	Method      string
	Path        string
	ServiceName string
}

func parseSpec(path string) ([]specRoute, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var doc struct {
		Paths map[string]map[string]struct {
			ServiceName string `yaml:"x-service-name"`
		} `yaml:"paths"`
	}

	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("YAML parse: %w", err)
	}

	var routes []specRoute
	for urlPath, methods := range doc.Paths {
		for method, op := range methods {
			if op.ServiceName == "" {
				continue
			}
			routes = append(routes, specRoute{
				Method:      capitalizeFirst(method),
				Path:        urlPath,
				ServiceName: op.ServiceName,
			})
		}
	}
	return routes, nil
}

func generateSpecRoutes(routes []specRoute, pkg, genPkg string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&buf, f, args...) }

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by apigen. DO NOT EDIT.\n\n")
	w("package %s\n\n", pkg)
	w("import (\n")
	w("\t\"context\"\n")
	w("\t\"os\"\n\n")
	w("\t\"github.com/gofiber/fiber/v3\"\n")
	w("\tgenerated %q\n", genPkg)
	w(")\n\n")

	w("type FetchFunc func(ctx context.Context, url string) ([]byte, error)\n\n")

	w("func RegisterRoutes(app *fiber.App, fetch FetchFunc) {\n")

	for _, r := range routes {
		envVar := "UPSTREAM_" + strings.ToUpper(r.ServiceName) + "_URL"
		funcName := "Transform" + exportedName(r.ServiceName)

		w("\tapp.%s(%q, func(c fiber.Ctx) error {\n", r.Method, r.Path)
		w("\t\tupstreamURL := os.Getenv(%q)\n", envVar)
		w("\t\tif upstreamURL == \"\" {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusServiceUnavailable, \"%s not configured\")\n", envVar)
		w("\t\t}\n\n")
		w("\t\tdata, err := fetch(c.Context(), upstreamURL)\n")
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\tresults, err := generated.%s(data)\n", funcName)
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\treturn c.JSON(results)\n")
		w("\t})\n\n")
	}

	w("}\n")
	return format.Source(buf.Bytes())
}

// --- Config mode (provider-aware) ---

type configRoute struct {
	Method   string
	Path     string
	FuncName string // e.g. "TransformDashboard"
	HasFetch bool   // uses $fetch() or $service() — needs aggregator + Execute func
	HasReq   bool   // uses $request() or $fetch with config — needs RequestContext
}

func parseConfig(path, jsonataDir string) ([]configRoute, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var cfg struct {
		Routes []struct {
			Path    string `yaml:"path"`
			Method  string `yaml:"method"`
			Jsonata string `yaml:"jsonata"`
		} `yaml:"routes"`
	}

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("YAML parse: %w", err)
	}

	var routes []configRoute
	for _, r := range cfg.Routes {
		baseName := strings.TrimSuffix(r.Jsonata, filepath.Ext(r.Jsonata))
		funcName := "Transform" + exportedName(baseName)

		jsonataPath := r.Jsonata
		if jsonataDir != "" {
			jsonataPath = filepath.Join(jsonataDir, r.Jsonata)
		}

		expr, err := os.ReadFile(jsonataPath)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", jsonataPath, err)
		}

		exprStr := string(expr)
		hasFetch := strings.Contains(exprStr, "$fetch(") || strings.Contains(exprStr, "$service(")
		hasReq := strings.Contains(exprStr, "$request(")

		routes = append(routes, configRoute{
			Method:   capitalizeFirst(r.Method),
			Path:     r.Path,
			FuncName: funcName,
			HasFetch: hasFetch,
			HasReq:   hasReq || hasFetch, // $fetch always uses RequestContext now
		})
	}
	return routes, nil
}

func generateConfigRoutes(routes []configRoute, pkg, genPkg string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&buf, f, args...) }

	needsAggregator := false
	needsDirectFetch := false
	needsRuntime := false
	for _, r := range routes {
		if r.HasFetch {
			needsAggregator = true
		} else if !r.HasReq {
			needsDirectFetch = true
		}
		if r.HasReq {
			needsRuntime = true
		}
	}

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by apigen from config.yaml. DO NOT EDIT.\n\n")
	w("package %s\n\n", pkg)
	w("import (\n")
	if needsDirectFetch {
		w("\t\"context\"\n")
		w("\t\"os\"\n")
	}
	w("\n")
	w("\t\"github.com/gofiber/fiber/v3\"\n")
	if needsAggregator {
		w("\t\"github.com/gcossani/ssfbff/internal/aggregator\"\n")
	}
	if needsRuntime {
		w("\t\"github.com/gcossani/ssfbff/runtime\"\n")
	}
	w("\tgenerated %q\n", genPkg)
	w(")\n\n")

	if needsDirectFetch {
		w("type FetchFunc func(ctx context.Context, url string) ([]byte, error)\n\n")
	}

	switch {
	case needsDirectFetch && needsAggregator:
		w("func RegisterRoutes(app *fiber.App, fetch FetchFunc, agg *aggregator.Aggregator) {\n")
	case needsAggregator:
		w("func RegisterRoutes(app *fiber.App, agg *aggregator.Aggregator) {\n")
	default:
		w("func RegisterRoutes(app *fiber.App, fetch FetchFunc) {\n")
	}

	for _, r := range routes {
		w("\tapp.%s(%q, func(c fiber.Ctx) error {\n", r.Method, r.Path)

		if r.HasFetch {
			// Provider/service mode: build request context, call the bundled Execute function.
			execName := strings.TrimPrefix(r.FuncName, "Transform")
			writeRequestContextBuilder(w, "\t\t")
			w("\t\tresult, err := generated.Execute%s(c.Context(), agg, reqCtx)\n", execName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tc.Set(\"Content-Type\", \"application/json\")\n")
			w("\t\treturn c.Send(result)\n")

		} else if r.HasReq {
			// Request-only mode: no upstream, just read request data.
			writeRequestContextBuilder(w, "\t\t")
			w("\t\tresult, err := generated.%s(reqCtx)\n", r.FuncName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tc.Set(\"Content-Type\", \"application/json\")\n")
			w("\t\treturn c.Send(result)\n")

		} else {
			// Filter mode: single upstream fetch, then transform.
			svcName := strings.TrimPrefix(r.FuncName, "Transform")
			envVar := "UPSTREAM_" + toEnvCase(svcName) + "_URL"

			w("\t\tupstreamURL := os.Getenv(%q)\n", envVar)
			w("\t\tif upstreamURL == \"\" {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusServiceUnavailable, \"%s not configured\")\n", envVar)
			w("\t\t}\n\n")
			w("\t\tdata, err := fetch(c.Context(), upstreamURL)\n")
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tresults, err := generated.%s(data)\n", r.FuncName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\treturn c.JSON(results)\n")
		}

		w("\t})\n\n")
	}

	w("}\n")
	return format.Source(buf.Bytes())
}

// writeRequestContextBuilder emits Go code that populates a runtime.RequestContext
// from the Fiber Ctx. We inline this rather than calling a helper function so the
// runtime package doesn't depend on Fiber.
func writeRequestContextBuilder(w func(string, ...any), indent string) {
	w("%sreqCtx := runtime.RequestContext{\n", indent)
	w("%s\tPath:   c.Path(),\n", indent)
	w("%s\tMethod: c.Method(),\n", indent)
	w("%s\tBody:   c.Body(),\n", indent)
	w("%s}\n", indent)

	// Fiber v3 exposes headers/cookies/query/params via individual getters.
	// We copy them into maps for the generated code. This is only done once
	// per request, so the allocation cost is negligible.
	w("%sc.Request().Header.VisitAll(func(key, val []byte) {\n", indent)
	w("%s\tif reqCtx.Headers == nil { reqCtx.Headers = map[string]string{} }\n", indent)
	w("%s\treqCtx.Headers[string(key)] = string(val)\n", indent)
	w("%s})\n", indent)

	w("%sc.Request().Header.VisitAllCookie(func(key, val []byte) {\n", indent)
	w("%s\tif reqCtx.Cookies == nil { reqCtx.Cookies = map[string]string{} }\n", indent)
	w("%s\treqCtx.Cookies[string(key)] = string(val)\n", indent)
	w("%s})\n", indent)

	w("%sreqCtx.Query = c.Queries()\n\n", indent)

	// Route params — Fiber v3 doesn't have AllParams(), so we iterate over
	// the param names from the matched route and read each value.
	w("%sif routeParams := c.Route().Params; len(routeParams) > 0 {\n", indent)
	w("%s\treqCtx.Params = make(map[string]string, len(routeParams))\n", indent)
	w("%s\tfor _, p := range routeParams {\n", indent)
	w("%s\t\treqCtx.Params[p] = c.Params(p)\n", indent)
	w("%s\t}\n", indent)
	w("%s}\n\n", indent)
}

// --- Helpers ---

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(strings.ToLower(s))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func exportedName(s string) string {
	acronyms := map[string]string{
		"id": "ID", "url": "URL", "api": "API", "http": "HTTP",
	}
	if v, ok := acronyms[strings.ToLower(s)]; ok {
		return v
	}
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if v, ok := acronyms[strings.ToLower(part)]; ok {
			b.WriteString(v)
		} else {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

// toEnvCase converts "Orders" -> "ORDERS", "UserService" -> "USER_SERVICE" etc.
// It inserts underscores before uppercase letters that follow lowercase letters.
func toEnvCase(s string) string {
	var buf strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			prev := rune(s[i-1])
			if unicode.IsLower(prev) {
				buf.WriteByte('_')
			}
		}
		buf.WriteRune(unicode.ToUpper(r))
	}
	return buf.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "apigen: "+format+"\n", args...)
	os.Exit(1)
}
