// Command apigen reads an OpenAPI spec and generates Fiber v3 route registration
// code. Each operation with an "x-service-name" extension is mapped to a
// pre-compiled JSONata transform function (TransformXxx) and an upstream URL
// sourced from an environment variable (UPSTREAM_XXX_URL).
//
// Usage:
//
//	go run ./cmd/apigen \
//	  --spec=api/openapi.yaml \
//	  --output=cmd/server/routes_gen.go \
//	  --package=main \
//	  --generated-pkg=github.com/example/project/internal/generated
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

func main() {
	spec := flag.String("spec", "", "path to OpenAPI YAML file")
	output := flag.String("output", "", "path for the generated .go file")
	pkg := flag.String("package", "main", "Go package name for the generated file")
	genPkg := flag.String("generated-pkg", "", "import path of the generated transform package")
	flag.Parse()

	if *spec == "" || *output == "" || *genPkg == "" {
		fatal("--spec, --output, and --generated-pkg are required")
	}

	routes, err := parseSpec(*spec)
	if err != nil {
		fatal("parsing spec: %v", err)
	}

	src, err := generateRoutes(routes, *pkg, *genPkg)
	if err != nil {
		fatal("generating routes: %v", err)
	}

	if err := os.WriteFile(*output, src, 0o644); err != nil {
		fatal("writing output: %v", err)
	}

	fmt.Fprintf(os.Stderr, "apigen: %s -> %s (%d routes)\n", *spec, *output, len(routes))
}

// route captures what we need from each OpenAPI operation.
type route struct {
	Method      string // "Get", "Post", etc.
	Path        string // e.g., "/api/v1/orders"
	ServiceName string // value of x-service-name
}

// parseSpec extracts routes with x-service-name from an OpenAPI YAML file.
// We parse just enough structure — no heavy OpenAPI library needed.
func parseSpec(path string) ([]route, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var doc struct {
		Paths map[string]map[string]struct {
			ServiceName string `yaml:"x-service-name"`
		} `yaml:"paths"`
	}

	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("YAML parse: %w", err)
	}

	var routes []route
	for urlPath, methods := range doc.Paths {
		for method, op := range methods {
			if op.ServiceName == "" {
				continue
			}
			routes = append(routes, route{
				Method:      capitalizeFirst(method),
				Path:        urlPath,
				ServiceName: op.ServiceName,
			})
		}
	}
	return routes, nil
}

func generateRoutes(routes []route, pkg, genPkg string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&buf, f, args...) }

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by apigen. DO NOT EDIT.\n\n")
	w("package %s\n\n", pkg)
	w("import (\n")
	w("\t\"context\"\n")
	w("\t\"os\"\n\n")
	w("\t\"github.com/gofiber/fiber/v3\"\n")
	w("\tgenerated %q\n", genPkg)
	w(")\n\n")

	w("// FetchFunc fetches raw JSON from an upstream service URL.\n")
	w("type FetchFunc func(ctx context.Context, url string) ([]byte, error)\n\n")

	w("// RegisterRoutes wires up all BFF endpoints from the OpenAPI spec.\n")
	w("// Each route fetches upstream data, applies a compiled transform, and responds.\n")
	w("func RegisterRoutes(app *fiber.App, fetch FetchFunc) {\n")

	for _, r := range routes {
		envVar := "UPSTREAM_" + strings.ToUpper(r.ServiceName) + "_URL"
		funcName := "Transform" + exportedName(r.ServiceName)

		w("\tapp.%s(%q, func(c fiber.Ctx) error {\n", r.Method, r.Path)
		w("\t\tupstreamURL := os.Getenv(%q)\n", envVar)
		w("\t\tif upstreamURL == \"\" {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusServiceUnavailable, \"%s not configured\")\n", envVar)
		w("\t\t}\n\n")
		w("\t\tdata, err := fetch(c.Context(), upstreamURL)\n")
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\tresults, err := generated.%s(data)\n", funcName)
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\treturn c.JSON(results)\n")
		w("\t})\n\n")
	}

	w("}\n")

	return format.Source(buf.Bytes())
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(strings.ToLower(s))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// exportedName converts a lowercase/snake_case name to an exported Go name.
func exportedName(s string) string {
	acronyms := map[string]string{
		"id": "ID", "url": "URL", "api": "API", "http": "HTTP",
	}
	if v, ok := acronyms[strings.ToLower(s)]; ok {
		return v
	}
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if v, ok := acronyms[strings.ToLower(part)]; ok {
			b.WriteString(v)
		} else {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "apigen: "+format+"\n", args...)
	os.Exit(1)
}
