// Command apigen generates Fiber v3 route registration code from either:
//   - an OpenAPI spec (--spec) with x-service-name extensions, or
//   - a routes file (--routes) listing path-to-jsonata mappings.
//
// Routes mode supports both filter-mode transforms (single upstream) and
// provider-mode transforms (multiple upstreams via aggregator). The mode is
// auto-detected by checking if the jsonata file uses $fetch() calls.
//
// Usage:
//
//	go run ./cmd/apigen \
//	  --spec=data/openapi.yaml \
//	  --output=cmd/server/routes_gen.go \
//	  --package=main \
//	  --generated-pkg=github.com/example/project/internal/generated
//
//	go run ./cmd/apigen \
//	  --routes=data/routes.yaml \
//	  --jsonata-dir=data/services \
//	  --output=cmd/server/routes_gen.go \
//	  --package=main \
//	  --generated-pkg=github.com/example/project/internal/generated
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

func main() {
	spec := flag.String("spec", "", "path to OpenAPI YAML file (legacy mode)")
	routesFile := flag.String("routes", "", "path to routes.yaml")
	jsonataDir := flag.String("jsonata-dir", "", "directory containing .jsonata files (used with --routes)")
	output := flag.String("output", "", "path for the generated .go file")
	pkg := flag.String("package", "main", "Go package name for the generated file")
	genPkg := flag.String("generated-pkg", "", "import path of the generated transform package")
	flag.Parse()

	if *output == "" || *genPkg == "" {
		fatal("--output and --generated-pkg are required")
	}

	hasSpec := *spec != ""
	hasRoutes := *routesFile != ""
	if !hasSpec && !hasRoutes {
		fatal("either --spec or --routes is required")
	}
	if hasSpec && hasRoutes {
		fatal("--spec and --routes are mutually exclusive")
	}

	var src []byte
	var routeCount int
	var sourceFile string

	if hasSpec {
		sourceFile = *spec
		routes, err := parseSpec(*spec)
		if err != nil {
			fatal("parsing spec: %v", err)
		}
		routeCount = len(routes)
		src, err = generateSpecRoutes(routes, *pkg, *genPkg)
		if err != nil {
			fatal("generating routes: %v", err)
		}
	} else {
		sourceFile = *routesFile
		routes, err := parseConfig(*routesFile, *jsonataDir)
		if err != nil {
			fatal("parsing routes: %v", err)
		}
		routeCount = len(routes)
		src, err = generateConfigRoutes(routes, *pkg, *genPkg)
		if err != nil {
			fatal("generating routes: %v", err)
		}
	}

	if err := os.WriteFile(*output, src, 0o644); err != nil {
		fatal("writing output: %v", err)
	}

	fmt.Fprintf(os.Stderr, "apigen: %s -> %s (%d routes)\n", sourceFile, *output, routeCount)
}

// --- OpenAPI spec mode (backward compatible) ---

type specRoute struct {
	Method      string
	Path        string
	ServiceName string
}

func parseSpec(path string) ([]specRoute, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var doc struct {
		Paths map[string]map[string]struct {
			ServiceName string `yaml:"x-service-name"`
		} `yaml:"paths"`
	}

	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("YAML parse: %w", err)
	}

	var routes []specRoute
	for urlPath, methods := range doc.Paths {
		for method, op := range methods {
			if op.ServiceName == "" {
				continue
			}
			routes = append(routes, specRoute{
				Method:      capitalizeFirst(method),
				Path:        urlPath,
				ServiceName: op.ServiceName,
			})
		}
	}
	return routes, nil
}

func generateSpecRoutes(routes []specRoute, pkg, genPkg string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&buf, f, args...) }

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by apigen. DO NOT EDIT.\n\n")
	w("package %s\n\n", pkg)
	w("import (\n")
	w("\t\"context\"\n")
	w("\t\"os\"\n\n")
	w("\t\"github.com/gofiber/fiber/v3\"\n")
	w("\tgenerated %q\n", genPkg)
	w(")\n\n")

	w("type FetchFunc func(ctx context.Context, url string) ([]byte, error)\n\n")

	w("func RegisterRoutes(app *fiber.App, fetch FetchFunc) {\n")

	for _, r := range routes {
		envVar := "UPSTREAM_" + strings.ToUpper(r.ServiceName) + "_URL"
		funcName := "Transform" + exportedName(r.ServiceName)

		w("\tapp.%s(%q, func(c fiber.Ctx) error {\n", r.Method, r.Path)
		w("\t\tupstreamURL := os.Getenv(%q)\n", envVar)
		w("\t\tif upstreamURL == \"\" {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusServiceUnavailable, \"%s not configured\")\n", envVar)
		w("\t\t}\n\n")
		w("\t\tdata, err := fetch(c.Context(), upstreamURL)\n")
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\tresults, err := generated.%s(data)\n", funcName)
		w("\t\tif err != nil {\n")
		w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
		w("\t\t}\n\n")
		w("\t\treturn c.JSON(results)\n")
		w("\t})\n\n")
	}

	w("}\n")
	return format.Source(buf.Bytes())
}

// --- Config mode (provider-aware) ---

type configRoute struct {
	Method   string
	Path     string
	FuncName string // e.g. "TransformDashboard"
	HasFetch bool   // uses $fetch() or $service() — needs aggregator + Execute func
	HasReq   bool   // uses $request() or $fetch with config — needs RequestContext
	ReqKeys  requestKeys // which request fields are actually referenced
}

// requestKeys tracks which specific request fields a JSONata expression uses.
// By extracting only the needed keys, we avoid copying all headers/cookies on
// every request — a significant win for high-throughput BFF servers.
type requestKeys struct {
	Headers []string // specific header names
	Cookies []string // specific cookie names
	Query   bool     // needs query params
	Params  bool     // needs route params
	Path    bool     // needs request path
	Method  bool     // needs HTTP method
	Body    bool     // needs request body
}

// reRequestField matches patterns like $request().headers.Authorization,
// $request().cookies.session, $request().query.page, $request().params.id,
// $request().path, $request().method, $request().body.
var reRequestField = regexp.MustCompile(`\$request\(\)\.(headers|cookies|query|params|path|method|body)(?:\.(\w+))?`)

func scanRequestKeys(expr string) requestKeys {
	var rk requestKeys
	seenHeaders := map[string]bool{}
	seenCookies := map[string]bool{}

	for _, match := range reRequestField.FindAllStringSubmatch(expr, -1) {
		kind := match[1]
		name := match[2]

		switch kind {
		case "headers":
			if name != "" && !seenHeaders[name] {
				seenHeaders[name] = true
				rk.Headers = append(rk.Headers, name)
			}
		case "cookies":
			if name != "" && !seenCookies[name] {
				seenCookies[name] = true
				rk.Cookies = append(rk.Cookies, name)
			}
		case "query":
			rk.Query = true
		case "params":
			rk.Params = true
		case "path":
			rk.Path = true
		case "method":
			rk.Method = true
		case "body":
			rk.Body = true
		}
	}
	return rk
}

func parseConfig(path, jsonataDir string) ([]configRoute, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var cfg struct {
		Routes []struct {
			Path    string `yaml:"path"`
			Method  string `yaml:"method"`
			Jsonata string `yaml:"jsonata"`
		} `yaml:"routes"`
	}

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("YAML parse: %w", err)
	}

	var routes []configRoute
	for _, r := range cfg.Routes {
		baseName := strings.TrimSuffix(r.Jsonata, filepath.Ext(r.Jsonata))
		funcName := "Transform" + exportedName(baseName)

		jsonataPath := r.Jsonata
		if jsonataDir != "" {
			jsonataPath = filepath.Join(jsonataDir, r.Jsonata)
		}

		expr, err := os.ReadFile(jsonataPath)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", jsonataPath, err)
		}

		exprStr := string(expr)
		hasFetch := strings.Contains(exprStr, "$fetch(") || strings.Contains(exprStr, "$service(")
		hasReq := strings.Contains(exprStr, "$request(")
		rk := scanRequestKeys(exprStr)

		routes = append(routes, configRoute{
			Method:   capitalizeFirst(r.Method),
			Path:     r.Path,
			FuncName: funcName,
			HasFetch: hasFetch,
			HasReq:   hasReq || hasFetch, // $fetch always uses RequestContext now
			ReqKeys:  rk,
		})
	}
	return routes, nil
}

func generateConfigRoutes(routes []configRoute, pkg, genPkg string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&buf, f, args...) }

	needsAggregator := false
	needsDirectFetch := false
	needsRuntime := false
	for _, r := range routes {
		if r.HasFetch {
			needsAggregator = true
		} else if !r.HasReq {
			needsDirectFetch = true
		}
		if r.HasReq {
			needsRuntime = true
		}
	}

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by apigen from routes.yaml. DO NOT EDIT.\n\n")
	w("package %s\n\n", pkg)
	w("import (\n")
	if needsDirectFetch {
		w("\t\"context\"\n")
		w("\t\"os\"\n")
	}
	w("\n")
	w("\t\"github.com/gofiber/fiber/v3\"\n")
	if needsAggregator {
		w("\t\"github.com/gcossani/ssfbff/internal/aggregator\"\n")
	}
	if needsRuntime {
		w("\t\"github.com/gcossani/ssfbff/runtime\"\n")
	}
	w("\tgenerated %q\n", genPkg)
	w(")\n\n")

	if needsDirectFetch {
		w("type FetchFunc func(ctx context.Context, url string) ([]byte, error)\n\n")
	}

	switch {
	case needsDirectFetch && needsAggregator:
		w("func RegisterRoutes(app *fiber.App, fetch FetchFunc, agg *aggregator.Aggregator) {\n")
	case needsAggregator:
		w("func RegisterRoutes(app *fiber.App, agg *aggregator.Aggregator) {\n")
	default:
		w("func RegisterRoutes(app *fiber.App, fetch FetchFunc) {\n")
	}

	for _, r := range routes {
		w("\tapp.%s(%q, func(c fiber.Ctx) error {\n", r.Method, r.Path)

		if r.HasFetch {
			// Provider/service mode: build request context, call the bundled Execute function.
			execName := strings.TrimPrefix(r.FuncName, "Transform")
			writeRequestContextBuilder(w, "\t\t", r.ReqKeys)
			w("\t\tresult, err := generated.Execute%s(c.Context(), agg, reqCtx)\n", execName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tc.Set(\"Content-Type\", \"application/json\")\n")
			w("\t\treturn c.Send(result)\n")

		} else if r.HasReq {
			// Request-only mode: no upstream, just read request data.
			writeRequestContextBuilder(w, "\t\t", r.ReqKeys)
			w("\t\tresult, err := generated.%s(reqCtx)\n", r.FuncName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tc.Set(\"Content-Type\", \"application/json\")\n")
			w("\t\treturn c.Send(result)\n")

		} else {
			// Filter mode: single upstream fetch, then transform.
			svcName := strings.TrimPrefix(r.FuncName, "Transform")
			envVar := "UPSTREAM_" + toEnvCase(svcName) + "_URL"

			w("\t\tupstreamURL := os.Getenv(%q)\n", envVar)
			w("\t\tif upstreamURL == \"\" {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusServiceUnavailable, \"%s not configured\")\n", envVar)
			w("\t\t}\n\n")
			w("\t\tdata, err := fetch(c.Context(), upstreamURL)\n")
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusBadGateway, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\tresults, err := generated.%s(data)\n", r.FuncName)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fiber.NewError(fiber.StatusInternalServerError, err.Error())\n")
			w("\t\t}\n\n")
			w("\t\treturn c.JSON(results)\n")
		}

		w("\t})\n\n")
	}

	w("}\n")
	return format.Source(buf.Bytes())
}

// writeRequestContextBuilder emits Go code that populates a runtime.RequestContext
// from the Fiber Ctx. It only extracts the specific fields that the JSONata expression
// actually references — no wasted work copying all headers/cookies on every request.
func writeRequestContextBuilder(w func(string, ...any), indent string, rk requestKeys) {
	w("%sreqCtx := runtime.RequestContext{}\n", indent)

	// Only extract specific headers that the expression references.
	if len(rk.Headers) > 0 {
		w("%sreqCtx.Headers = map[string]string{\n", indent)
		for _, h := range rk.Headers {
			w("%s\t%q: c.Get(%q),\n", indent, h, h)
		}
		w("%s}\n", indent)
	}

	// Only extract specific cookies.
	if len(rk.Cookies) > 0 {
		w("%sreqCtx.Cookies = map[string]string{\n", indent)
		for _, c := range rk.Cookies {
			w("%s\t%q: c.Cookies(%q),\n", indent, c, c)
		}
		w("%s}\n", indent)
	}

	if rk.Query {
		w("%sreqCtx.Query = c.Queries()\n", indent)
	}

	if rk.Params {
		w("%sif routeParams := c.Route().Params; len(routeParams) > 0 {\n", indent)
		w("%s\treqCtx.Params = make(map[string]string, len(routeParams))\n", indent)
		w("%s\tfor _, p := range routeParams {\n", indent)
		w("%s\t\treqCtx.Params[p] = c.Params(p)\n", indent)
		w("%s\t}\n", indent)
		w("%s}\n", indent)
	}

	if rk.Path {
		w("%sreqCtx.Path = c.Path()\n", indent)
	}

	if rk.Method {
		w("%sreqCtx.Method = c.Method()\n", indent)
	}

	if rk.Body {
		w("%sreqCtx.Body = c.Body()\n", indent)
	}

	w("\n")
}

// --- Helpers ---

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(strings.ToLower(s))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func exportedName(s string) string {
	acronyms := map[string]string{
		"id": "ID", "url": "URL", "api": "API", "http": "HTTP",
	}
	if v, ok := acronyms[strings.ToLower(s)]; ok {
		return v
	}
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if v, ok := acronyms[strings.ToLower(part)]; ok {
			b.WriteString(v)
		} else {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

// toEnvCase converts "Orders" -> "ORDERS", "UserService" -> "USER_SERVICE" etc.
// It inserts underscores before uppercase letters that follow lowercase letters.
func toEnvCase(s string) string {
	var buf strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			prev := rune(s[i-1])
			if unicode.IsLower(prev) {
				buf.WriteByte('_')
			}
		}
		buf.WriteRune(unicode.ToUpper(r))
	}
	return buf.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "apigen: "+format+"\n", args...)
	os.Exit(1)
}
