package transpiler

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// Generate produces formatted Go source code from a QueryPlan.
// The generated code uses jsontext.Decoder for streaming JSON navigation
// and json/v2.UnmarshalDecode for typed per-element deserialization.
func Generate(plan *QueryPlan, packageName, sourceFile, expression string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(format string, args ...any) {
		fmt.Fprintf(&buf, format, args...)
	}

	writeHeader(&buf, w, packageName, sourceFile, expression)
	writeInputStructs(&buf, w, plan)
	writeOutputStruct(&buf, w, plan)
	writeTransformFunc(&buf, w, plan)

	return format.Source(buf.Bytes())
}

func writeHeader(buf *bytes.Buffer, w func(string, ...any), pkg, sourceFile, expr string) {
	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by jsonata-transpiler. DO NOT EDIT.\n")
	if sourceFile != "" {
		w("// Source: %s\n", sourceFile)
	}
	w("// Expression: %s\n\n", expr)
	w("package %s\n\n", pkg)
	w("import (\n")
	w("\t\"bytes\"\n")
	w("\t\"encoding/json/jsontext\"\n")
	w("\tjsonv2 \"encoding/json/v2\"\n")
	w("\t\"fmt\"\n")
	w(")\n\n")
}

func writeInputStructs(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	// Write nested structs first (for array fields with children).
	for _, f := range plan.InputFields {
		if f.IsArray && len(f.Children) > 0 {
			w("type %s struct {\n", unexportedName(f.GoName)+"Item")
			for _, child := range f.Children {
				w("\t%s %s `json:\"%s\"`\n", child.GoName, child.GoType, child.JSONName)
			}
			w("}\n\n")
		}
	}

	// Write the main input struct.
	structName := unexportedName(plan.RootField) + "Element"
	w("type %s struct {\n", structName)
	for _, f := range plan.InputFields {
		if f.IsArray {
			itemType := unexportedName(f.GoName) + "Item"
			w("\t%s []%s `json:\"%s\"`\n", f.GoName, itemType, f.JSONName)
		} else {
			w("\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONName)
		}
	}
	w("}\n\n")
}

func writeOutputStruct(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	w("type %s struct {\n", plan.OutputName)
	for _, f := range plan.OutputFields {
		w("\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONName)
	}
	w("}\n\n")
}

func writeTransformFunc(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	elemType := unexportedName(plan.RootField) + "Element"
	outType := plan.OutputName

	w("func %s(data []byte) ([]%s, error) {\n", plan.FuncName, outType)
	w("\tdec := jsontext.NewDecoder(bytes.NewReader(data))\n\n")

	// Navigate into the root object.
	w("\ttok, err := dec.ReadToken()\n")
	w("\tif err != nil {\n")
	w("\t\treturn nil, fmt.Errorf(\"reading root: %%w\", err)\n")
	w("\t}\n")
	w("\tif tok.Kind() != '{' {\n")
	w("\t\treturn nil, fmt.Errorf(\"expected JSON object at root, got %%v\", tok.Kind())\n")
	w("\t}\n\n")

	w("\tvar results []%s\n\n", outType)

	// Stream through top-level fields looking for the target array.
	w("\tfor dec.PeekKind() != '}' {\n")
	w("\t\tnameTok, err := dec.ReadToken()\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading field name: %%w\", err)\n")
	w("\t\t}\n\n")

	w("\t\tif nameTok.String() != %q {\n", plan.RootField)
	w("\t\t\tif err := dec.SkipValue(); err != nil {\n")
	w("\t\t\t\treturn nil, fmt.Errorf(\"skipping field: %%w\", err)\n")
	w("\t\t\t}\n")
	w("\t\t\tcontinue\n")
	w("\t\t}\n\n")

	// Found the target array — consume '['.
	w("\t\tarrTok, err := dec.ReadToken()\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading array start: %%w\", err)\n")
	w("\t\t}\n")
	w("\t\tif arrTok.Kind() != '[' {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"expected array for %s, got %%v\", arrTok.Kind())\n", plan.RootField)
	w("\t\t}\n\n")

	// Process each element in the array.
	w("\t\tfor dec.PeekKind() != ']' {\n")
	w("\t\t\tvar elem %s\n", elemType)
	w("\t\t\tif err := jsonv2.UnmarshalDecode(dec, &elem); err != nil {\n")
	w("\t\t\t\treturn nil, fmt.Errorf(\"reading element: %%w\", err)\n")
	w("\t\t\t}\n\n")

	// Apply filters.
	if len(plan.Filters) > 0 {
		conditions := make([]string, len(plan.Filters))
		for i, f := range plan.Filters {
			conditions[i] = fmt.Sprintf("elem.%s %s %s", f.FieldGoName, f.Op, f.Literal)
		}
		allConditions := strings.Join(conditions, " && ")
		w("\t\t\tpassesFilter := %s\n", allConditions)
		w("\t\t\tif !passesFilter {\n")
		w("\t\t\t\tcontinue\n")
		w("\t\t\t}\n\n")
	}

	// Compute aggregations before building the result.
	for _, out := range plan.OutputFields {
		if out.AggregateFunc == "" {
			continue
		}
		varName := unexportedName(out.GoName) + "Agg"
		switch out.AggregateFunc {
		case "sum":
			w("\t\t\tvar %s float64\n", varName)
			w("\t\t\tfor _, v := range elem.%s {\n", out.AggregateArray)
			w("\t\t\t\t%s += v.%s\n", varName, out.AggregateField)
			w("\t\t\t}\n\n")
		case "count":
			w("\t\t\t%s := float64(len(elem.%s))\n\n", varName, out.AggregateArray)
		default:
			w("\t\t\t// TODO: unsupported aggregate function $%s\n", out.AggregateFunc)
			w("\t\t\tvar %s float64\n\n", varName)
		}
	}

	// Build the output struct.
	w("\t\t\tresults = append(results, %s{\n", outType)
	for _, out := range plan.OutputFields {
		if out.AggregateFunc != "" {
			varName := unexportedName(out.GoName) + "Agg"
			w("\t\t\t\t%s: %s,\n", out.GoName, varName)
		} else {
			w("\t\t\t\t%s: elem.%s,\n", out.GoName, out.SourceField)
		}
	}
	w("\t\t\t})\n")
	w("\t\t}\n\n")

	// Consume ']'.
	w("\t\tif _, err := dec.ReadToken(); err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading array end: %%w\", err)\n")
	w("\t\t}\n")
	w("\t}\n\n")

	w("\treturn results, nil\n")
	w("}\n")
}

// GenerateProvider produces Go source code from a ProviderPlan.
// It emits:
//   - A Deps function that builds the list of upstream calls (with optional
//     method/headers/body from the request context)
//   - A transform function that assembles the output JSON from fetched results
//     and/or request context data
func GenerateProvider(plan *ProviderPlan, packageName, sourceFile, expression string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(format string, args ...any) {
		fmt.Fprintf(&buf, format, args...)
	}

	hasDeps := len(plan.Deps) > 0
	hasFetchConfig := planHasFetchConfig(plan)

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by jsonata-transpiler. DO NOT EDIT.\n")
	if sourceFile != "" {
		w("// Source: %s\n", sourceFile)
	}
	w("// Expression: %s\n\n", expression)
	w("package %s\n\n", packageName)
	w("import (\n")
	w("\t\"bytes\"\n")
	w("\t\"encoding/json/jsontext\"\n")
	if hasDeps {
		w("\t\"fmt\"\n")
	}
	w("\n")
	w("\t\"github.com/gcossani/ssfbff/runtime\"\n")
	w(")\n\n")

	// --- Deps function ---
	writeProviderDepsFunc(w, plan, hasFetchConfig)

	// --- Transform function ---
	writeProviderTransformFunc(w, plan, hasDeps)

	return format.Source(buf.Bytes())
}

func writeProviderDepsFunc(w func(string, ...any), plan *ProviderPlan, hasFetchConfig bool) {
	if len(plan.Deps) == 0 {
		return
	}

	// Deps is always a function now (accepts RequestContext), so the aggregator
	// can receive per-request method/headers/body built from the incoming request.
	w("func %sDeps(req runtime.RequestContext) []runtime.ProviderDep {\n", plan.FuncName)
	w("\treturn []runtime.ProviderDep{\n")

	for _, field := range plan.Fields {
		if field.Kind != "fetch" {
			continue
		}

		if field.FetchConfig == nil {
			w("\t\t{Provider: %q, Endpoint: %q},\n", field.Provider, field.Endpoint)
			continue
		}

		cfg := field.FetchConfig
		w("\t\t{\n")
		w("\t\t\tProvider: %q,\n", field.Provider)
		w("\t\t\tEndpoint: %q,\n", field.Endpoint)

		if cfg.Method != "" {
			w("\t\t\tMethod: %q,\n", cfg.Method)
		}

		if len(cfg.Headers) > 0 {
			w("\t\t\tHeaders: map[string]string{\n")
			for _, h := range cfg.Headers {
				w("\t\t\t\t%q: %s,\n", h.Key, configValueToGoExpr(h.Value, "req"))
			}
			w("\t\t\t},\n")
		}

		if len(cfg.Body) > 0 {
			// Build body JSON inline using jsontext.Encoder.
			w("\t\t\tBody: func() []byte {\n")
			w("\t\t\t\tvar b bytes.Buffer\n")
			w("\t\t\t\te := jsontext.NewEncoder(&b)\n")
			w("\t\t\t\te.WriteToken(jsontext.BeginObject)\n")
			for _, entry := range cfg.Body {
				w("\t\t\t\te.WriteToken(jsontext.String(%q))\n", entry.Key)
				writeConfigValueToken(w, entry.Value, "req", "\t\t\t\t")
			}
			w("\t\t\t\te.WriteToken(jsontext.EndObject)\n")
			w("\t\t\t\treturn b.Bytes()\n")
			w("\t\t\t}(),\n")
		}

		w("\t\t},\n")
	}

	w("\t}\n")
	w("}\n\n")
}

func writeProviderTransformFunc(w func(string, ...any), plan *ProviderPlan, hasDeps bool) {
	// The transform always accepts RequestContext — it's zero-cost when unused
	// and keeps the signature uniform for the generated handler.
	if hasDeps {
		w("func %s(results map[string][]byte, req runtime.RequestContext) ([]byte, error) {\n", plan.FuncName)
	} else {
		w("func %s(req runtime.RequestContext) ([]byte, error) {\n", plan.FuncName)
	}

	w("\tvar buf bytes.Buffer\n")
	w("\tenc := jsontext.NewEncoder(&buf)\n\n")
	w("\tenc.WriteToken(jsontext.BeginObject)\n\n")

	for _, field := range plan.Fields {
		w("\tenc.WriteToken(jsontext.String(%q))\n", field.OutputKey)

		switch field.Kind {
		case "fetch":
			depKey := field.Provider + "." + field.Endpoint
			if len(field.JSONPath) > 0 {
				pathArgs := ""
				for _, p := range field.JSONPath {
					pathArgs += fmt.Sprintf(", %q", p)
				}
				varName := "val" + exportedName(field.OutputKey)
				w("\t%s, err := runtime.ExtractPath(results[%q]%s)\n", varName, depKey, pathArgs)
				w("\tif err != nil {\n")
				w("\t\treturn nil, fmt.Errorf(\"extracting %s.%s.%s: %%w\", err)\n",
					field.Provider, field.Endpoint, strings.Join(field.JSONPath, "."))
				w("\t}\n")
				w("\tenc.WriteValue(%s)\n\n", varName)
			} else {
				w("\tenc.WriteValue(results[%q])\n\n", depKey)
			}

		case "header", "cookie", "query", "param":
			mapName := requestFuncToMap(field.Kind)
			w("\tenc.WriteToken(jsontext.String(req.%s[%q]))\n\n", mapName, field.Arg)

		case "path":
			w("\tenc.WriteToken(jsontext.String(req.Path))\n\n")

		case "method":
			w("\tenc.WriteToken(jsontext.String(req.Method))\n\n")

		case "body":
			if len(field.BodyPath) > 0 {
				pathArgs := ""
				for _, p := range field.BodyPath {
					pathArgs += fmt.Sprintf(", %q", p)
				}
				varName := "val" + exportedName(field.OutputKey)
				w("\t%s, err := runtime.ExtractPath(req.Body%s)\n", varName, pathArgs)
				w("\tif err != nil {\n")
				w("\t\treturn nil, fmt.Errorf(\"extracting body.%s: %%w\", err)\n",
					strings.Join(field.BodyPath, "."))
				w("\t}\n")
				w("\tenc.WriteValue(%s)\n\n", varName)
			} else {
				w("\tenc.WriteValue(req.Body)\n\n")
			}

		case "static":
			w("\tenc.WriteToken(jsontext.String(%q))\n\n", field.StaticValue)
		}
	}

	w("\tenc.WriteToken(jsontext.EndObject)\n")
	w("\treturn buf.Bytes(), nil\n")
	w("}\n")
}

// configValueToGoExpr returns a Go expression string for a ConfigValue.
func configValueToGoExpr(cv ConfigValue, reqVar string) string {
	switch cv.Kind {
	case "static":
		return fmt.Sprintf("%q", cv.Static)
	case "header", "cookie", "query", "param":
		return fmt.Sprintf("%s.%s[%q]", reqVar, requestFuncToMap(cv.Kind), cv.Arg)
	case "path":
		return reqVar + ".Path"
	case "method":
		return reqVar + ".Method"
	default:
		return `""`
	}
}

// writeConfigValueToken writes the code to emit a single config value into
// a jsontext.Encoder. Used for building $fetch() body JSON.
func writeConfigValueToken(w func(string, ...any), cv ConfigValue, reqVar, indent string) {
	switch cv.Kind {
	case "static":
		w("%se.WriteToken(jsontext.String(%q))\n", indent, cv.Static)
	case "header", "cookie", "query", "param":
		mapName := requestFuncToMap(cv.Kind)
		w("%se.WriteToken(jsontext.String(%s.%s[%q]))\n", indent, reqVar, mapName, cv.Arg)
	case "path":
		w("%se.WriteToken(jsontext.String(%s.Path))\n", indent, reqVar)
	case "method":
		w("%se.WriteToken(jsontext.String(%s.Method))\n", indent, reqVar)
	case "body":
		if len(cv.Path) > 0 {
			pathArgs := ""
			for _, p := range cv.Path {
				pathArgs += fmt.Sprintf(", %q", p)
			}
			w("%sbodyVal, _ := runtime.ExtractPath(%s.Body%s)\n", indent, reqVar, pathArgs)
			w("%se.WriteValue(bodyVal)\n", indent)
		} else {
			w("%se.WriteValue(%s.Body)\n", indent, reqVar)
		}
	}
}

func requestFuncToMap(kind string) string {
	switch kind {
	case "header":
		return "Headers"
	case "cookie":
		return "Cookies"
	case "query":
		return "Query"
	case "param":
		return "Params"
	default:
		return "Headers"
	}
}

func planHasFetchConfig(plan *ProviderPlan) bool {
	for _, f := range plan.Fields {
		if f.FetchConfig != nil {
			return true
		}
	}
	return false
}

// unexportedName returns a lowercase version of a Go name for local variables/types.
func unexportedName(s string) string {
	if s == "" {
		return s
	}
	// Handle all-caps names like "ID" -> "id"
	if strings.ToUpper(s) == s {
		return strings.ToLower(s)
	}
	runes := []rune(s)
	runes[0] = rune(strings.ToLower(string(runes[0]))[0])
	return string(runes)
}
