package transpiler

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// Generate produces formatted Go source code from a QueryPlan.
// The generated code uses jsontext.Decoder for streaming JSON navigation
// and json/v2.UnmarshalDecode for typed per-element deserialization.
func Generate(plan *QueryPlan, packageName, sourceFile, expression string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(format string, args ...any) {
		fmt.Fprintf(&buf, format, args...)
	}

	writeHeader(&buf, w, packageName, sourceFile, expression, plan)
	writeInputStructs(&buf, w, plan)
	writeOutputStruct(&buf, w, plan)
	writeTransformFunc(&buf, w, plan)

	return format.Source(buf.Bytes())
}

func writeHeader(buf *bytes.Buffer, w func(string, ...any), pkg, sourceFile, expr string, plan *QueryPlan) {
	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by jsonata-transpiler. DO NOT EDIT.\n")
	if sourceFile != "" {
		w("// Source: %s\n", sourceFile)
	}
	w("// Expression: %s\n\n", expr)
	w("package %s\n\n", pkg)
	w("import (\n")
	w("\t\"bytes\"\n")
	w("\t\"encoding/json/jsontext\"\n")
	w("\tjsonv2 \"encoding/json/v2\"\n")
	w("\t\"fmt\"\n")
	if plan.NeedsRuntime() {
		w("\n\t\"github.com/gcossani/ssfbff/runtime\"\n")
	}
	w(")\n\n")
}

func writeInputStructs(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	// Write nested structs first (for array fields with children).
	for _, f := range plan.InputFields {
		if f.IsArray && len(f.Children) > 0 {
			w("type %s struct {\n", unexportedName(f.GoName)+"Item")
			for _, child := range f.Children {
				w("\t%s %s `json:\"%s\"`\n", child.GoName, child.GoType, child.JSONName)
			}
			w("}\n\n")
		}
	}

	// Write the main input struct.
	structName := unexportedName(plan.RootField) + "Element"
	w("type %s struct {\n", structName)
	for _, f := range plan.InputFields {
		if f.IsArray {
			itemType := unexportedName(f.GoName) + "Item"
			w("\t%s []%s `json:\"%s\"`\n", f.GoName, itemType, f.JSONName)
		} else {
			w("\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONName)
		}
	}
	w("}\n\n")
}

func writeOutputStruct(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	w("type %s struct {\n", plan.OutputName)
	for _, f := range plan.OutputFields {
		w("\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONName)
	}
	w("}\n\n")
}

func writeTransformFunc(buf *bytes.Buffer, w func(string, ...any), plan *QueryPlan) {
	elemType := unexportedName(plan.RootField) + "Element"
	outType := plan.OutputName

	w("func %s(data []byte) ([]%s, error) {\n", plan.FuncName, outType)
	w("\tdec := jsontext.NewDecoder(bytes.NewReader(data))\n\n")

	// Navigate into the root object.
	w("\ttok, err := dec.ReadToken()\n")
	w("\tif err != nil {\n")
	w("\t\treturn nil, fmt.Errorf(\"reading root: %%w\", err)\n")
	w("\t}\n")
	w("\tif tok.Kind() != '{' {\n")
	w("\t\treturn nil, fmt.Errorf(\"expected JSON object at root, got %%v\", tok.Kind())\n")
	w("\t}\n\n")

	w("\tvar results []%s\n\n", outType)

	// Stream through top-level fields looking for the target array.
	w("\tfor dec.PeekKind() != '}' {\n")
	w("\t\tnameTok, err := dec.ReadToken()\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading field name: %%w\", err)\n")
	w("\t\t}\n\n")

	w("\t\tif nameTok.String() != %q {\n", plan.RootField)
	w("\t\t\tif err := dec.SkipValue(); err != nil {\n")
	w("\t\t\t\treturn nil, fmt.Errorf(\"skipping field: %%w\", err)\n")
	w("\t\t\t}\n")
	w("\t\t\tcontinue\n")
	w("\t\t}\n\n")

	// Found the target array — consume '['.
	w("\t\tarrTok, err := dec.ReadToken()\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading array start: %%w\", err)\n")
	w("\t\t}\n")
	w("\t\tif arrTok.Kind() != '[' {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"expected array for %s, got %%v\", arrTok.Kind())\n", plan.RootField)
	w("\t\t}\n\n")

	// Process each element in the array.
	w("\t\tfor dec.PeekKind() != ']' {\n")
	w("\t\t\tvar elem %s\n", elemType)
	w("\t\t\tif err := jsonv2.UnmarshalDecode(dec, &elem); err != nil {\n")
	w("\t\t\t\treturn nil, fmt.Errorf(\"reading element: %%w\", err)\n")
	w("\t\t\t}\n\n")

	em := &exprEmitter{w: w, indent: "\t\t\t", elemVar: "elem"}

	// Apply filters.
	if len(plan.Filters) > 0 {
		conditions := make([]string, len(plan.Filters))
		for i, f := range plan.Filters {
			conditions[i] = em.emit(f)
		}
		allConditions := strings.Join(conditions, " && ")
		w("\t\t\tpassesFilter := %s\n", allConditions)
		w("\t\t\tif !passesFilter {\n")
		w("\t\t\t\tcontinue\n")
		w("\t\t\t}\n\n")
	}

	// Pre-compute output field values (aggregates need for loops emitted first).
	outputExprs := make([]string, len(plan.OutputFields))
	for i, out := range plan.OutputFields {
		outputExprs[i] = em.emit(out.Value)
	}

	// Build the output struct.
	w("\t\t\tresults = append(results, %s{\n", outType)
	for i, out := range plan.OutputFields {
		w("\t\t\t\t%s: %s,\n", out.GoName, outputExprs[i])
	}
	w("\t\t\t})\n")
	w("\t\t}\n\n")

	// Consume ']'.
	w("\t\tif _, err := dec.ReadToken(); err != nil {\n")
	w("\t\t\treturn nil, fmt.Errorf(\"reading array end: %%w\", err)\n")
	w("\t\t}\n")
	w("\t}\n\n")

	w("\treturn results, nil\n")
	w("}\n")
}

// ---------------------------------------------------------------------------
// exprEmitter — walks an Expr tree and produces Go code
// ---------------------------------------------------------------------------
// It writes pre-computation lines (for loops, conditionals) directly to w
// and returns a Go expression string that can be used inline.

type exprEmitter struct {
	w       func(string, ...any)
	indent  string
	elemVar string
	counter int
}

func (em *exprEmitter) emit(e *Expr) string {
	if e == nil {
		return "nil"
	}
	switch e.Kind {
	case "field":
		return em.elemVar + "." + e.FieldName

	case "arrayField":
		return em.elemVar + "." + e.ArrayName

	case "literal":
		return e.LiteralValue

	case "binary":
		return em.emitBinary(e)

	case "unary":
		operand := em.emit(e.Left)
		return fmt.Sprintf("(-%s)", operand)

	case "conditional":
		return em.emitConditional(e)

	case "funcCall":
		return em.emitFuncCall(e)

	default:
		return "nil"
	}
}

func (em *exprEmitter) emitBinary(e *Expr) string {
	left := em.emit(e.Left)
	right := em.emit(e.Right)

	if e.Op == "&" {
		return fmt.Sprintf("runtime.ToString(%s) + runtime.ToString(%s)", left, right)
	}
	return fmt.Sprintf("(%s %s %s)", left, e.Op, right)
}

func (em *exprEmitter) emitConditional(e *Expr) string {
	em.counter++
	varName := fmt.Sprintf("cond%d", em.counter)
	cond := em.emit(e.Cond)
	thenVal := em.emit(e.Then)

	goType := e.GoType
	if goType == "" || goType == "any" {
		goType = "any"
	}

	em.w("%svar %s %s\n", em.indent, varName, goType)
	em.w("%sif runtime.Truthy(%s) {\n", em.indent, cond)
	em.w("%s\t%s = %s\n", em.indent, varName, thenVal)
	if e.Else != nil {
		elseVal := em.emit(e.Else)
		em.w("%s} else {\n", em.indent)
		em.w("%s\t%s = %s\n", em.indent, varName, elseVal)
	}
	em.w("%s}\n", em.indent)

	return varName
}

func (em *exprEmitter) emitFuncCall(e *Expr) string {
	// Aggregate functions with an arrayField argument need a pre-computation loop.
	if isAggregateFunc(e.FuncName) && len(e.FuncArgs) == 1 && e.FuncArgs[0].Kind == "arrayField" {
		return em.emitAggregate(e)
	}

	// All other functions map directly to runtime.* calls.
	args := make([]string, len(e.FuncArgs))
	for i, arg := range e.FuncArgs {
		args[i] = em.emit(arg)
	}
	return em.mapFuncCall(e.FuncName, args)
}

func (em *exprEmitter) emitAggregate(e *Expr) string {
	em.counter++
	af := e.FuncArgs[0]
	varName := fmt.Sprintf("agg%d", em.counter)

	switch e.FuncName {
	case "sum":
		em.w("%svar %s float64\n", em.indent, varName)
		em.w("%sfor _, v := range %s.%s {\n", em.indent, em.elemVar, af.ArrayName)
		em.w("%s\t%s += v.%s\n", em.indent, varName, af.ChildName)
		em.w("%s}\n", em.indent)

	case "count":
		em.w("%s%s := float64(len(%s.%s))\n", em.indent, varName, em.elemVar, af.ArrayName)

	case "min", "max", "average":
		sliceVar := varName + "Slice"
		em.w("%svar %s []float64\n", em.indent, sliceVar)
		em.w("%sfor _, v := range %s.%s {\n", em.indent, em.elemVar, af.ArrayName)
		em.w("%s\t%s = append(%s, v.%s)\n", em.indent, sliceVar, sliceVar, af.ChildName)
		em.w("%s}\n", em.indent)

		runtimeFn := map[string]string{"min": "MinFloat64", "max": "MaxFloat64", "average": "AverageFloat64"}
		em.w("%s%s := runtime.%s(%s)\n", em.indent, varName, runtimeFn[e.FuncName], sliceVar)
	}

	return varName
}

func (em *exprEmitter) mapFuncCall(name string, args []string) string {
	all := strings.Join(args, ", ")
	switch name {
	// String functions
	case "string":
		return fmt.Sprintf("runtime.ToString(%s)", all)
	case "length":
		return fmt.Sprintf("runtime.Length(%s)", all)
	case "substring":
		return fmt.Sprintf("runtime.Substring(%s)", all)
	case "substringBefore":
		return fmt.Sprintf("runtime.SubstringBefore(%s)", all)
	case "substringAfter":
		return fmt.Sprintf("runtime.SubstringAfter(%s)", all)
	case "uppercase":
		return fmt.Sprintf("runtime.Uppercase(%s)", all)
	case "lowercase":
		return fmt.Sprintf("runtime.Lowercase(%s)", all)
	case "trim":
		return fmt.Sprintf("runtime.Trim(%s)", all)
	case "contains":
		return fmt.Sprintf("runtime.Contains(%s)", all)
	case "join":
		return fmt.Sprintf("runtime.JoinArray(%s)", all)

	// Numeric functions
	case "number":
		return fmt.Sprintf("runtime.ToNumber(%s)", all)
	case "abs":
		return fmt.Sprintf("runtime.Abs(%s)", all)
	case "floor":
		return fmt.Sprintf("runtime.Floor(%s)", all)
	case "ceil":
		return fmt.Sprintf("runtime.Ceil(%s)", all)
	case "round":
		return fmt.Sprintf("runtime.Round(%s)", all)

	// Boolean functions
	case "boolean":
		return fmt.Sprintf("runtime.ToBoolean(%s)", all)
	case "not":
		return fmt.Sprintf("runtime.Not(%s)", all)
	case "exists":
		return fmt.Sprintf("runtime.Exists(%s)", all)

	// Array/object functions
	case "sort":
		return fmt.Sprintf("runtime.SortArray(%s)", all)
	case "reverse":
		return fmt.Sprintf("runtime.ReverseArray(%s)", all)
	case "append":
		return fmt.Sprintf("runtime.AppendArray(%s)", all)
	case "distinct":
		return fmt.Sprintf("runtime.DistinctArray(%s)", all)
	case "keys":
		return fmt.Sprintf("runtime.KeysMap(%s)", all)
	case "merge":
		return fmt.Sprintf("runtime.MergeArray(%s)", all)
	case "type":
		return fmt.Sprintf("runtime.TypeOf(%s)", all)

	default:
		return fmt.Sprintf("nil /* unsupported: $%s(%s) */", name, all)
	}
}

// GenerateProvider produces Go source code from a ProviderPlan.
// It emits:
//   - A Deps function that builds the list of upstream calls (with optional
//     method/headers/body from the request context)
//   - A transform function that assembles the output JSON from fetched results
//     and/or request context data
//   - An Execute function that bundles the full pipeline: deps + fetch +
//     sub-services + transform (only when the plan has deps or services)
func GenerateProvider(plan *ProviderPlan, packageName, sourceFile, expression string) ([]byte, error) {
	var buf bytes.Buffer
	w := func(format string, args ...any) {
		fmt.Fprintf(&buf, format, args...)
	}

	hasDeps := len(plan.Deps) > 0
	hasServices := len(plan.Services) > 0
	needsExecute := hasDeps || hasServices

	w("//go:build goexperiment.jsonv2\n\n")
	w("// Code generated by jsonata-transpiler. DO NOT EDIT.\n")
	if sourceFile != "" {
		w("// Source: %s\n", sourceFile)
	}
	w("// Expression: %s\n\n", expression)
	w("package %s\n\n", packageName)
	w("import (\n")
	w("\t\"bytes\"\n")
	if needsExecute {
		w("\t\"context\"\n")
	}
	w("\t\"encoding/json/jsontext\"\n")
	if hasDeps || hasServices {
		w("\t\"fmt\"\n")
	}
	if hasServices {
		w("\t\"sync\"\n")
	}
	w("\n")
	if needsExecute {
		w("\t\"github.com/gcossani/ssfbff/internal/aggregator\"\n")
	}
	w("\t\"github.com/gcossani/ssfbff/runtime\"\n")
	if hasServices {
		w("\t\"golang.org/x/sync/errgroup\"\n")
	}
	w(")\n\n")

	// --- Deps function ---
	writeProviderDepsFunc(w, plan, false)

	// --- Transform function ---
	writeProviderTransformFunc(w, plan, hasDeps || hasServices)

	// --- Execute function (bundles deps + fetch + sub-services + transform) ---
	if needsExecute {
		writeExecuteFunc(w, plan)
	}

	return format.Source(buf.Bytes())
}

func writeProviderDepsFunc(w func(string, ...any), plan *ProviderPlan, _ bool) {
	if len(plan.Deps) == 0 {
		return
	}

	// Deps is always a function now (accepts RequestContext), so the aggregator
	// can receive per-request method/headers/body built from the incoming request.
	w("func %sDeps(req runtime.RequestContext) []runtime.ProviderDep {\n", plan.FuncName)
	w("\treturn []runtime.ProviderDep{\n")

	// Deduplicate: only emit one dep per unique provider+endpoint pair,
	// using the config from the first field that references it.
	seen := map[string]bool{}
	for _, field := range plan.Fields {
		if field.Kind != "fetch" {
			continue
		}
		depKey := field.Provider + "." + field.Endpoint
		if seen[depKey] {
			continue
		}
		seen[depKey] = true

		if field.FetchConfig == nil {
			w("\t\t{Provider: %q, Endpoint: %q},\n", field.Provider, field.Endpoint)
			continue
		}

		cfg := field.FetchConfig
		w("\t\t{\n")
		w("\t\t\tProvider: %q,\n", field.Provider)
		w("\t\t\tEndpoint: %q,\n", field.Endpoint)

		if cfg.Method != "" {
			w("\t\t\tMethod: %q,\n", cfg.Method)
		}

		if len(cfg.Headers) > 0 {
			w("\t\t\tHeaders: map[string]string{\n")
			for _, h := range cfg.Headers {
				w("\t\t\t\t%q: %s,\n", h.Key, configValueToGoExpr(h.Value, "req"))
			}
			w("\t\t\t},\n")
		}

		if len(cfg.Body) > 0 {
			// Build body JSON inline using jsontext.Encoder.
			w("\t\t\tBody: func() []byte {\n")
			w("\t\t\t\tvar b bytes.Buffer\n")
			w("\t\t\t\te := jsontext.NewEncoder(&b)\n")
			w("\t\t\t\te.WriteToken(jsontext.BeginObject)\n")
			for _, entry := range cfg.Body {
				w("\t\t\t\te.WriteToken(jsontext.String(%q))\n", entry.Key)
				writeConfigValueToken(w, entry.Value, "req", "\t\t\t\t")
			}
			w("\t\t\t\te.WriteToken(jsontext.EndObject)\n")
			w("\t\t\t\treturn b.Bytes()\n")
			w("\t\t\t}(),\n")
		}

		w("\t\t},\n")
	}

	w("\t}\n")
	w("}\n\n")
}

func writeProviderTransformFunc(w func(string, ...any), plan *ProviderPlan, hasDeps bool) {
	// The transform always accepts RequestContext — it's zero-cost when unused
	// and keeps the signature uniform for the generated handler.
	if hasDeps {
		w("func %s(results map[string][]byte, req runtime.RequestContext) ([]byte, error) {\n", plan.FuncName)
	} else {
		w("func %s(req runtime.RequestContext) ([]byte, error) {\n", plan.FuncName)
	}

	w("\tvar buf bytes.Buffer\n")
	w("\tenc := jsontext.NewEncoder(&buf)\n\n")
	w("\tenc.WriteToken(jsontext.BeginObject)\n\n")

	for _, field := range plan.Fields {
		w("\tenc.WriteToken(jsontext.String(%q))\n", field.OutputKey)

		switch field.Kind {
		case "fetch":
			depKey := field.Provider + "." + field.Endpoint
			if len(field.JSONPath) > 0 {
				pathArgs := ""
				for _, p := range field.JSONPath {
					pathArgs += fmt.Sprintf(", %q", p)
				}
				varName := "val" + exportedName(field.OutputKey)
				w("\t%s, err := runtime.ExtractPath(results[%q]%s)\n", varName, depKey, pathArgs)
				w("\tif err != nil {\n")
				w("\t\treturn nil, fmt.Errorf(\"extracting %s.%s.%s: %%w\", err)\n",
					field.Provider, field.Endpoint, strings.Join(field.JSONPath, "."))
				w("\t}\n")
				w("\tenc.WriteValue(%s)\n\n", varName)
			} else {
				w("\tenc.WriteValue(results[%q])\n\n", depKey)
			}

		case "header", "cookie", "query", "param":
			mapName := requestFuncToMap(field.Kind)
			w("\tenc.WriteToken(jsontext.String(req.%s[%q]))\n\n", mapName, field.Arg)

		case "path":
			w("\tenc.WriteToken(jsontext.String(req.Path))\n\n")

		case "method":
			w("\tenc.WriteToken(jsontext.String(req.Method))\n\n")

		case "body":
			if len(field.BodyPath) > 0 {
				pathArgs := ""
				for _, p := range field.BodyPath {
					pathArgs += fmt.Sprintf(", %q", p)
				}
				varName := "val" + exportedName(field.OutputKey)
				w("\t%s, err := runtime.ExtractPath(req.Body%s)\n", varName, pathArgs)
				w("\tif err != nil {\n")
				w("\t\treturn nil, fmt.Errorf(\"extracting body.%s: %%w\", err)\n",
					strings.Join(field.BodyPath, "."))
				w("\t}\n")
				w("\tenc.WriteValue(%s)\n\n", varName)
			} else {
				w("\tenc.WriteValue(req.Body)\n\n")
			}

		case "service":
			svcKey := "$service." + field.ServiceName
			if len(field.JSONPath) > 0 {
				pathArgs := ""
				for _, p := range field.JSONPath {
					pathArgs += fmt.Sprintf(", %q", p)
				}
				varName := "val" + exportedName(field.OutputKey)
				w("\t%s, err := runtime.ExtractPath(results[%q]%s)\n", varName, svcKey, pathArgs)
				w("\tif err != nil {\n")
				w("\t\treturn nil, fmt.Errorf(\"extracting %s.%s: %%w\", err)\n",
					field.ServiceName, strings.Join(field.JSONPath, "."))
				w("\t}\n")
				w("\tenc.WriteValue(%s)\n\n", varName)
			} else {
				w("\tenc.WriteValue(results[%q])\n\n", svcKey)
			}

		case "static":
			w("\tenc.WriteToken(jsontext.String(%q))\n\n", field.StaticValue)
		}
	}

	w("\tenc.WriteToken(jsontext.EndObject)\n")
	w("\treturn buf.Bytes(), nil\n")
	w("}\n")
}

// writeExecuteFunc emits a function that bundles the full service pipeline:
// 1. Build deps and fetch all providers in parallel
// 2. Run all sub-services in parallel
// 3. Call the transform with the combined results
func writeExecuteFunc(w func(string, ...any), plan *ProviderPlan) {
	baseName := strings.TrimPrefix(plan.FuncName, "Transform")
	hasDeps := len(plan.Deps) > 0
	hasServices := len(plan.Services) > 0

	w("func Execute%s(ctx context.Context, agg *aggregator.Aggregator, req runtime.RequestContext) ([]byte, error) {\n", baseName)

	if hasDeps {
		w("\tdeps := %sDeps(req)\n", plan.FuncName)
		w("\tresults, err := agg.Fetch(ctx, deps)\n")
		w("\tif err != nil {\n")
		w("\t\treturn nil, fmt.Errorf(\"%s: fetch: %%w\", err)\n", baseName)
		w("\t}\n\n")
	} else {
		w("\tresults := make(map[string][]byte)\n\n")
	}

	if hasServices {
		w("\tg, gctx := errgroup.WithContext(ctx)\n")
		w("\tvar mu sync.Mutex\n\n")
		for _, svc := range plan.Services {
			execFn := "Execute" + exportedName(svc)
			svcKey := "$service." + svc
			w("\tg.Go(func() error {\n")
			w("\t\tr, err := %s(gctx, agg, req)\n", execFn)
			w("\t\tif err != nil {\n")
			w("\t\t\treturn fmt.Errorf(\"service %s: %%w\", err)\n", svc)
			w("\t\t}\n")
			w("\t\tmu.Lock()\n")
			w("\t\tresults[%q] = r\n", svcKey)
			w("\t\tmu.Unlock()\n")
			w("\t\treturn nil\n")
			w("\t})\n\n")
		}
		w("\tif err := g.Wait(); err != nil {\n")
		w("\t\treturn nil, err\n")
		w("\t}\n\n")
	}

	w("\treturn %s(results, req)\n", plan.FuncName)
	w("}\n\n")
}

// configValueToGoExpr returns a Go expression string for a ConfigValue.
func configValueToGoExpr(cv ConfigValue, reqVar string) string {
	switch cv.Kind {
	case "static":
		return fmt.Sprintf("%q", cv.Static)
	case "header", "cookie", "query", "param":
		return fmt.Sprintf("%s.%s[%q]", reqVar, requestFuncToMap(cv.Kind), cv.Arg)
	case "path":
		return reqVar + ".Path"
	case "method":
		return reqVar + ".Method"
	default:
		return `""`
	}
}

// writeConfigValueToken writes the code to emit a single config value into
// a jsontext.Encoder. Used for building $fetch() body JSON.
func writeConfigValueToken(w func(string, ...any), cv ConfigValue, reqVar, indent string) {
	switch cv.Kind {
	case "static":
		w("%se.WriteToken(jsontext.String(%q))\n", indent, cv.Static)
	case "header", "cookie", "query", "param":
		mapName := requestFuncToMap(cv.Kind)
		w("%se.WriteToken(jsontext.String(%s.%s[%q]))\n", indent, reqVar, mapName, cv.Arg)
	case "path":
		w("%se.WriteToken(jsontext.String(%s.Path))\n", indent, reqVar)
	case "method":
		w("%se.WriteToken(jsontext.String(%s.Method))\n", indent, reqVar)
	case "body":
		if len(cv.Path) > 0 {
			pathArgs := ""
			for _, p := range cv.Path {
				pathArgs += fmt.Sprintf(", %q", p)
			}
			w("%sbodyVal, _ := runtime.ExtractPath(%s.Body%s)\n", indent, reqVar, pathArgs)
			w("%se.WriteValue(bodyVal)\n", indent)
		} else {
			w("%se.WriteValue(%s.Body)\n", indent, reqVar)
		}
	}
}

func requestFuncToMap(kind string) string {
	switch kind {
	case "header":
		return "Headers"
	case "cookie":
		return "Cookies"
	case "query":
		return "Query"
	case "param":
		return "Params"
	default:
		return "Headers"
	}
}

func planHasFetchConfig(plan *ProviderPlan) bool {
	for _, f := range plan.Fields {
		if f.FetchConfig != nil {
			return true
		}
	}
	return false
}

// unexportedName returns a lowercase version of a Go name for local variables/types.
func unexportedName(s string) string {
	if s == "" {
		return s
	}
	// Handle all-caps names like "ID" -> "id"
	if strings.ToUpper(s) == s {
		return strings.ToLower(s)
	}
	runes := []rune(s)
	runes[0] = rune(strings.ToLower(string(runes[0]))[0])
	return string(runes)
}
