#!/bin/sh
# Script to regenerate internal/generated/generate.go based on actual JSONata files
# This keeps the generate.go file in sync with the data/services/ directory
#
# Usage:
#   ./scripts/generate-generate-go.sh [OPTIONS]
#
# Options:
#   --project-root DIR    Project root directory (default: script's parent)
#   --data-dir DIR        Data directory (default: $PROJECT_ROOT/data)
#   --module-path PATH    Go module path (default: github.com/gcossani/ssfbff)
#   --output FILE         Output file path (default: $PROJECT_ROOT/internal/generated/generate.go)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DATA_DIR=""
MODULE_PATH="github.com/gcossani/ssfbff"
OUTPUT_FILE=""

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --data-dir)
      DATA_DIR="$2"
      shift 2
      ;;
    --module-path)
      MODULE_PATH="$2"
      shift 2
      ;;
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --project-root DIR    Project root directory (default: script's parent)"
      echo "  --data-dir DIR        Data directory (default: \$PROJECT_ROOT/data)"
      echo "  --module-path PATH    Go module path (default: github.com/gcossani/ssfbff)"
      echo "  --output FILE         Output file path (default: \$PROJECT_ROOT/internal/generated/generate.go)"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

# Set defaults
if [ -z "$DATA_DIR" ]; then
  DATA_DIR="$PROJECT_ROOT/data"
fi

if [ -z "$OUTPUT_FILE" ]; then
  OUTPUT_FILE="$PROJECT_ROOT/internal/generated/generate.go"
fi

SERVICES_DIR="$DATA_DIR/services"
OPENAPI_FILE="$DATA_DIR/openapi.yaml"
PROXIES_FILE="$DATA_DIR/proxies.yaml"
ROUTES_FILE="$DATA_DIR/routes.yaml"

# Check if services directory exists
if [ ! -d "$SERVICES_DIR" ]; then
  echo "Error: services directory not found: $SERVICES_DIR"
  exit 1
fi

# Count JSONata files
JSONATA_COUNT=$(find "$SERVICES_DIR" -name "*.jsonata" 2>/dev/null | wc -l)
if [ "$JSONATA_COUNT" -eq 0 ]; then
  echo "Warning: No .jsonata files found in $SERVICES_DIR"
fi

# Calculate relative path from generate.go location to data directory
# generate.go is at: $PROJECT_ROOT/internal/generated/generate.go
# data dir is at: $DATA_DIR
# Relative path from internal/generated/ to data/ is: ../../data (if standard layout)
RELATIVE_DATA_PATH="../../data"
if [ "$DATA_DIR" != "$PROJECT_ROOT/data" ]; then
  # If data dir is different, calculate relative path
  # This is a simplified approach - assumes data dir is a subdirectory of project root
  RELATIVE_DATA_PATH="../../$(basename "$DATA_DIR")"
fi

# Create output directory if it doesn't exist
OUTPUT_DIR=$(dirname "$OUTPUT_FILE")
mkdir -p "$OUTPUT_DIR"
if [ $? -ne 0 ]; then
  echo "Error: Failed to create output directory: $OUTPUT_DIR"
  exit 1
fi

# Generate the file
cat > "$OUTPUT_FILE" << EOF
//go:build goexperiment.jsonv2

// Package generated contains Go transform functions produced by the JSONata
// transpiler and route registration code produced by the API generator.
//
// Do not edit the *_gen.go files by hand — they are regenerated by:
//
//	GOEXPERIMENT=jsonv2 go generate ./internal/generated/
//
// To regenerate this file from data/services/, run:
//
//	./scripts/generate-generate-go.sh
package generated

EOF

# Add go:generate directives for each JSONata file
for jsonata_file in "$SERVICES_DIR"/*.jsonata; do
  if [ -f "$jsonata_file" ]; then
    filename=$(basename "$jsonata_file" .jsonata)
    echo "//go:generate go run ../../cmd/transpiler --input=$RELATIVE_DATA_PATH/services/$filename.jsonata --output=${filename}_gen.go --package=generated" >> "$OUTPUT_FILE"
  fi
done

# Add apigen directive

if [ -f "$OPENAPI_FILE" ]; then
  PROXIES_ARG=""
  if [ -f "$PROXIES_FILE" ]; then
    PROXIES_ARG="--proxies=$RELATIVE_DATA_PATH/proxies.yaml"
  fi
  echo "//go:generate go run ../../cmd/apigen --spec=$RELATIVE_DATA_PATH/openapi.yaml --jsonata-dir=$RELATIVE_DATA_PATH/services $PROXIES_ARG --output=../../cmd/server/routes_gen.go --package=main --generated-pkg=$MODULE_PATH/internal/generated" >> "$OUTPUT_FILE"
elif [ -f "$ROUTES_FILE" ]; then
  echo "//go:generate go run ../../cmd/apigen --routes=$RELATIVE_DATA_PATH/routes.yaml --jsonata-dir=$RELATIVE_DATA_PATH/services --output=../../cmd/server/routes_gen.go --package=main --generated-pkg=$MODULE_PATH/internal/generated" >> "$OUTPUT_FILE"
else
  echo "Warning: Neither openapi.yaml nor routes.yaml found in $DATA_DIR"
fi

echo "✅ Generated $OUTPUT_FILE"
echo "   Found $JSONATA_COUNT JSONata file(s)"
