//go:build goexperiment.jsonv2

// Code generated by apigen. DO NOT EDIT.

package main

import (
	"context"
	"os"

	generated "github.com/gcossani/ssfbff/internal/generated"
	"github.com/gofiber/fiber/v3"
)

// FetchFunc fetches raw JSON from an upstream service URL.
type FetchFunc func(ctx context.Context, url string) ([]byte, error)

// RegisterRoutes wires up all BFF endpoints from the OpenAPI spec.
// Each route fetches upstream data, applies a compiled transform, and responds.
func RegisterRoutes(app *fiber.App, fetch FetchFunc) {
	app.Get("/api/v1/orders", func(c fiber.Ctx) error {
		upstreamURL := os.Getenv("UPSTREAM_ORDERS_URL")
		if upstreamURL == "" {
			return fiber.NewError(fiber.StatusServiceUnavailable, "UPSTREAM_ORDERS_URL not configured")
		}

		data, err := fetch(c.Context(), upstreamURL)
		if err != nil {
			return fiber.NewError(fiber.StatusBadGateway, err.Error())
		}

		results, err := generated.TransformOrders(data)
		if err != nil {
			return fiber.NewError(fiber.StatusInternalServerError, err.Error())
		}

		return c.JSON(results)
	})

	app.Get("/api/v1/products", func(c fiber.Ctx) error {
		upstreamURL := os.Getenv("UPSTREAM_PRODUCTS_URL")
		if upstreamURL == "" {
			return fiber.NewError(fiber.StatusServiceUnavailable, "UPSTREAM_PRODUCTS_URL not configured")
		}

		data, err := fetch(c.Context(), upstreamURL)
		if err != nil {
			return fiber.NewError(fiber.StatusBadGateway, err.Error())
		}

		results, err := generated.TransformProducts(data)
		if err != nil {
			return fiber.NewError(fiber.StatusInternalServerError, err.Error())
		}

		return c.JSON(results)
	})

}
