//go:build goexperiment.jsonv2

// Code generated by apigen from config.yaml. DO NOT EDIT.

package main

import (
	"context"
	"os"

	"github.com/gcossani/ssfbff/internal/aggregator"
	generated "github.com/gcossani/ssfbff/internal/generated"
	"github.com/gofiber/fiber/v3"
)

type FetchFunc func(ctx context.Context, url string) ([]byte, error)

func RegisterRoutes(app *fiber.App, fetch FetchFunc, agg *aggregator.Aggregator) {
	app.Get("/dashboard", func(c fiber.Ctx) error {
		fetched, err := agg.Fetch(c.Context(), generated.TransformDashboardDeps)
		if err != nil {
			return fiber.NewError(fiber.StatusBadGateway, err.Error())
		}

		result, err := generated.TransformDashboard(fetched)
		if err != nil {
			return fiber.NewError(fiber.StatusInternalServerError, err.Error())
		}

		c.Set("Content-Type", "application/json")
		return c.Send(result)
	})

	app.Get("/api/v1/orders", func(c fiber.Ctx) error {
		upstreamURL := os.Getenv("UPSTREAM_ORDERS_URL")
		if upstreamURL == "" {
			return fiber.NewError(fiber.StatusServiceUnavailable, "UPSTREAM_ORDERS_URL not configured")
		}

		data, err := fetch(c.Context(), upstreamURL)
		if err != nil {
			return fiber.NewError(fiber.StatusBadGateway, err.Error())
		}

		results, err := generated.TransformOrders(data)
		if err != nil {
			return fiber.NewError(fiber.StatusInternalServerError, err.Error())
		}

		return c.JSON(results)
	})

	app.Get("/api/v1/products", func(c fiber.Ctx) error {
		upstreamURL := os.Getenv("UPSTREAM_PRODUCTS_URL")
		if upstreamURL == "" {
			return fiber.NewError(fiber.StatusServiceUnavailable, "UPSTREAM_PRODUCTS_URL not configured")
		}

		data, err := fetch(c.Context(), upstreamURL)
		if err != nil {
			return fiber.NewError(fiber.StatusBadGateway, err.Error())
		}

		results, err := generated.TransformProducts(data)
		if err != nil {
			return fiber.NewError(fiber.StatusInternalServerError, err.Error())
		}

		return c.JSON(results)
	})

}
